spring:
  application:
    name: lm-sprint
  datasource:
    url: jdbc:postgresql://localhost:5433/lamuralla
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    driver-class-name: org.postgresql.Driver
server:
  port: 8089
app:
  cors:
    allowed-origins: https://cartagenacorporation.com,https://www.cartagenacorporation.com
  jwt:
    secret: ${JWT_SECRET}
project:
  service:
    url: http://localhost:8082/api/projects
issues:
  service:
    url: http://localhost:8090/api/issues
