spring:
  application:
    name: lm-sprint
  datasource:
    url: jdbc:postgresql://localhost:5432/lamuralla
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
server:
  port: '8089'
app:
  cors:
    allowed-origins: http://localhost:3000
  jwt:
    secret: ${JWT_SECRET}
project:
  service:
    url: http://localhost:8082/api/projects
issues:
  service:
    url: http://localhost:8080/api/issues
